// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marks.proto

#include "marks.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace MarksNS {
constexpr Marks::Marks(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : loaction_(){}
struct MarksDefaultTypeInternal {
  constexpr MarksDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~MarksDefaultTypeInternal() {}
  union {
    Marks _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT MarksDefaultTypeInternal _Marks_default_instance_;
}  // namespace MarksNS
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_marks_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_marks_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_marks_2eproto = nullptr;

const uint32_t TableStruct_marks_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MarksNS::Marks, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::MarksNS::Marks, loaction_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::MarksNS::Marks)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::MarksNS::_Marks_default_instance_),
};

const char descriptor_table_protodef_marks_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\013marks.proto\022\007MarksNS\"\031\n\005Marks\022\020\n\010loact"
  "ion\030\001 \003(\014B\033\n\rcom.iov.protoB\nMarksProtob\006"
  "proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_marks_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_marks_2eproto = {
  false, false, 86, descriptor_table_protodef_marks_2eproto, "marks.proto", 
  &descriptor_table_marks_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_marks_2eproto::offsets,
  file_level_metadata_marks_2eproto, file_level_enum_descriptors_marks_2eproto, file_level_service_descriptors_marks_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_marks_2eproto_getter() {
  return &descriptor_table_marks_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_marks_2eproto(&descriptor_table_marks_2eproto);
namespace MarksNS {

// ===================================================================

class Marks::_Internal {
 public:
};

Marks::Marks(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  loaction_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:MarksNS.Marks)
}
Marks::Marks(const Marks& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      loaction_(from.loaction_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:MarksNS.Marks)
}

inline void Marks::SharedCtor() {
}

Marks::~Marks() {
  // @@protoc_insertion_point(destructor:MarksNS.Marks)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Marks::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Marks::ArenaDtor(void* object) {
  Marks* _this = reinterpret_cast< Marks* >(object);
  (void)_this;
}
void Marks::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Marks::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Marks::Clear() {
// @@protoc_insertion_point(message_clear_start:MarksNS.Marks)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  loaction_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Marks::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated bytes loaction = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_loaction();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Marks::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MarksNS.Marks)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated bytes loaction = 1;
  for (int i = 0, n = this->_internal_loaction_size(); i < n; i++) {
    const auto& s = this->_internal_loaction(i);
    target = stream->WriteBytes(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MarksNS.Marks)
  return target;
}

size_t Marks::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MarksNS.Marks)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated bytes loaction = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(loaction_.size());
  for (int i = 0, n = loaction_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
      loaction_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Marks::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Marks::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Marks::GetClassData() const { return &_class_data_; }

void Marks::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Marks *>(to)->MergeFrom(
      static_cast<const Marks &>(from));
}


void Marks::MergeFrom(const Marks& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MarksNS.Marks)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  loaction_.MergeFrom(from.loaction_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Marks::CopyFrom(const Marks& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MarksNS.Marks)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Marks::IsInitialized() const {
  return true;
}

void Marks::InternalSwap(Marks* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  loaction_.InternalSwap(&other->loaction_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Marks::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_marks_2eproto_getter, &descriptor_table_marks_2eproto_once,
      file_level_metadata_marks_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace MarksNS
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::MarksNS::Marks* Arena::CreateMaybeMessage< ::MarksNS::Marks >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MarksNS::Marks >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
